github: [metadata]
theme: jekyll-theme-hacker
title: Mason Robotics
description: Information about robotics in Mason, MI, including FIRST LEGO League
# google_analytics: [Your Google Analytics tracking ID]
navigation:
 - title: Home
   url: /index.html
 - title: FLL
   url: /fll.html
 - title: Resources
   url: /resources.html
